version: '3'
services:
  postgres:
    image: postgres:9.5
    environment:
      - "POSTGRES_USER=panoptes"
      - "POSTGRES_PASSWORD=panoptes"
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server --appendonly yes

  panoptes:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/rails_app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:30o00"
    command: ["/app/docker/start.sh"]
    environment:
      - "RAILS_ENV=development"
      - "DATABASE_URL=postgresql://panoptes:panoptes@pg"
      - "REDIS_URL=redis://redis:6379/0"
      - "DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true"
      - "DISABLE_SPRING=true"
    links:
      - redis:redis
      - postgres:pg

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/rails_app
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    command: ["/app/docker/start-sidekiq.sh"]
    environment:
      - "RAILS_ENV=development"
      - "DATABASE_URL=postgresql://panoptes:panoptes@pg"
      - "REDIS_URL=redis://redis:6379/0"
      - "DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true"
      - "DISABLE_SPRING=true"
    links:
      - redis:redis
      - postgres:pg

volumes:
  gem_cache: