postgres:
  image: postgres:9.4
  environment:
    - "POSTGRES_USER=panoptes"
    - "POSTGRES_PASSWORD=panoptes"
  ports:
    - "5432:5432"

redis:
  image: redis
  command: redis-server --appendonly yes
  # ports:
  #   - "6379:6379"

cellect:
  image: zooniverse/cellect-panoptes
  ports:
    - "4000:80"
  environment:
    - "RACK_ENV=development"
    #cellect registers a hostname but no port, so we need prod port 80
    - "PUMA_PORT=80"
    - "PUMA_MAX_THREADS=16"
    - "DEBUG_CELLECT_START=true"
    - "DATABASE_URL=postgresql://panoptes:panoptes@pg:5432/panoptes_development?pool=16"
    - "ATTENTION_REDIS_URL=redis://redis:6379/1"
  links:
    - redis
    - postgres:pg

gem_cache:
  image: busybox
  volumes:
    - /gem_cache

panoptes:
  dockerfile: Dockerfile.dev
  build: ./
  volumes:
    - ./:/rails_app
  volumes_from:
    - gem_cache
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=development"
    - "CELLECT_MIN_POOL_SIZE=100"
    - "ATTENTION_REDIS_URL=redis://redis:6379/1"
    - "BUNDLE_PATH=/gem_cache"
    - "BUNDLE_BIN=/gem_cache/bin"
  links:
    - redis:redis
    - postgres:pg
